# NumPy

In [1]:
import numpy as np

In [50]:
#1 dimensional Array
arr_1d = np.arange(0,11)
arr_1d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [51]:
#2nd way of creating 1d array
my_arr = [1,2,3]
arr = np.array(my_arr)
arr

array([1, 2, 3])

In [52]:
#2 Dimensional Array
#First way of creating 2d array
my_arr2 = [[1,2,3],[4,5,6],[7,8,9]]
np.array(my_arr2)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [53]:
#2nd way of creating 2d array
arrayx = np.array([[1,2,3],[4,5,6]])
arrayx

array([[1, 2, 3],
       [4, 5, 6]])

In [49]:
#3rd way of creating 2d array
array_2d = np.arange(0,50).reshape(5,10)#5 rows 10 coulmns
array_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [ ]:
#Range Function
print(np.arange(2,10))
print(np.arange(2,10,3))

In [ ]:
#Zeros List
print(np.zeros(6))
#Passing a tuple for matrices
print(np.zeros((3,4)))

In [ ]:
#Ones List
print(np.ones(5))
#Passing a tuple for matrices
print(np.ones((2,4)))

In [ ]:
#Identity Matices
print(np.eye(5))

In [ ]:
#linspace
#Show 100 numbers start from zero to 5  
np.linspace(0,5,50)

In [ ]:
#Getting random number in uniform distribution from 0 to 1
print(np.random.rand(2))
#Passing tuple for matrices
print(np.random.rand(3,6))

In [ ]:
#Getting random number in normal distribution from 0 to 1
print(np.random.randn(2))
#Passing tuple for matrices
print(np.random.randn(3,6))

In [ ]:
#random int
#Select Random integer first argue is lowest and 2nd is highest you want
print(np.random.randint(1,50))
#3rd argue is for how many numbers you want
print(np.random.randint(1,50,10))

In [ ]:
arr_z = np.arange(25)
arr_z

In [ ]:
#Reshaping the array
arr_z.reshape(5,5)

In [ ]:
arr_x = np.random.randint(0,25,10)
print(arr_x)

In [ ]:
#Finding Max and Min from List
print(arr_x.max())
print(arr_x.min())

In [ ]:
#Finding the index position of min and max of array
print(arr_x.argmax())
print(arr_x.argmin())

In [ ]:
#Shape of Array, (x,) means array is 1D, (x,y) means array is 2D
arr_x.shape

# NumPy Class 2

Indexing and relation of 1D NumPy array

In [ ]:
arr3 = np.arange(0,10)
arr3

In [ ]:
#Numpy array starts from index 0
arr3[5]

In [ ]:
print(arr3[1:5])
print(arr3[:3])
print(arr3[0:])

In [ ]:
#Broadcasting an array
arr3[3:5] = 100
arr3

In [ ]:
arr3[6:9] = [11,12,13]
arr3

In [ ]:
arr3 = np.arange(0,10)
arr3

In [ ]:
#Slicing is storing some part of an existing array into a new variable and in normal python array it stores the values
aaa = [1,2,3,4,5,6,7,8]
ac = aaa[0:5]
ac[4] = [15,19]
print(ac)
print(aaa)

In [ ]:
#But in numpy array it doesn't store it just view from pre-existing array 
#and any change will be in the array not in new variable
za = arr3 [3:7]
print(za)

In [ ]:
za [:] = 100
print(za)
print(arr3)

In [ ]:
#And if you wanna change array's s part you can make a copy of it
xa = arr3.copy()
xa[:]=100
xa

In [ ]:
arr3

Indexing and selection of 2d array

In [4]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
#getting a row
print(arr2d [0])
print(arr2d [1])
print(arr2d [2])

In [ ]:
#There are two ways for getting certain value(2nd one is recomended)
#Getting one value(1st bracket for row 2nd for coulmn)
print(arr2d [0][2])
print(arr2d [1][2])
print(arr2d [2][0])

In [30]:
#Recomended Way
print(arr2d [0,2])
print(arr2d [1,2])
print(arr2d [2,0])

3
6
7


In [20]:
#Picking more than 1 index value from matices
print(arr2d[:2]) #it means it will grab everything till row 1

[[1 2 3]
 [4 5 6]]


In [21]:
print(arr2d[:2,1]) #will grab coulmn [1] from 1st 2 rows

[2 5]


In [22]:
#arr2d[x:x,y:y] x shows the rows from where to start and where to end
#and y shows the coulmns.
print(arr2d[:2,1:]) #it wil grab from start to [1] row and from coulmn 1 to end

[[2 3]
 [5 6]]


In [29]:
arr2d[1:,0:2]

array([[4, 5],
       [7, 8]])

Conditional Selection

In [32]:
arrc = np.arange(1,11)
arrc

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [35]:
#This is what we are doing in condiotional selection
barr = arrc >5
print(barr)
print(arrc[barr])

[False False False False False  True  True  True  True  True]
[ 6  7  8  9 10]


In [36]:
#But instead of above method we will use this short method
arrc[arrc > 5]

array([ 6,  7,  8,  9, 10])

In [48]:
print(arrc[arrc<3])
print(arrc[arrc<=5])
print(arrc[arrc == 1])

[1 2]
[1 2 3 4 5]
[1]


# NumPy Class 3

In [2]:
#Performing operations on array
arra = np.arange(1,11)
arra

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
#adding
print(arra+arra)
print(arra + 10)

[ 2  4  6  8 10 12 14 16 18 20]
[11 12 13 14 15 16 17 18 19 20]


In [12]:
#Subtracting
print(arra-arra)
print(arra-2)

[0 0 0 0 0 0 0 0 0 0]
[-1  0  1  2  3  4  5  6  7  8]


In [13]:
#Multiplying
print(arra*arra)
print(arra*5)

[  1   4   9  16  25  36  49  64  81 100]
[ 5 10 15 20 25 30 35 40 45 50]


In [14]:
#Dividing
print(arra/arra)
print(arra/5)
print(5/arra)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[0.2 0.4 0.6 0.8 1.  1.2 1.4 1.6 1.8 2. ]
[5.         2.5        1.66666667 1.25       1.         0.83333333
 0.71428571 0.625      0.55555556 0.5       ]


In [16]:
#Getting square 
arra**2

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [17]:
#Getting squareroot 
np.sqrt(arra)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])

In [18]:
np.sin(arra)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111])

In [19]:
np.log(arra)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509])

# Quiz

In [24]:
aa = np.arange(5)

In [29]:
aa[1:5]=5

In [30]:
aa

array([5, 5, 5, 5, 5])

In [31]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [36]:
aza = np.array([[1,2,3],[4,5,6],[7,8,9]])
aza

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [54]:
azza = [[1,2,3],[4,5,6],[7,8,9]]
azza = np.array(azza)
azza

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [57]:
np.sum(azza)

45

In [51]:
np.sum(azza[])

45

In [52]:
np.std(azza)

2.581988897471611

In [43]:
a3 = np.arange(12,22)

In [44]:
a3

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21])

In [45]:
a3[0]

12

In [46]:
a3[10]

IndexError: index 10 is out of bounds for axis 0 with size 10

In [48]:
a4 = [1,2,3,4,5]
a4[0]

1